apiVersion: v1
kind: Service
metadata:
  name: pomerium-verify
  labels:
    app.kubernetes.io/name: verify
    service: verify
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app.kubernetes.io/name: pomerium-verify
