apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "pomerium-zero.labels" . | nindent 4 }}
  name: pomerium-zero
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "pomerium-zero.labels" . | nindent 4 }}
  name: pomerium-zero
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - patch
  resourceNames:
  - {{ include "pomerium-zero.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "pomerium-zero.labels" . | nindent 4 }}
  name: pomerium-zero
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pomerium-zero
subjects:
- kind: ServiceAccount
  name: pomerium-zero
  namespace: {{ .Release.Namespace }}
